title: Oh hi
theme: minima
description: > # this means to ignore newlines until "baseurl:"
show_excerpts: true # set to false to remove excerpts on the homepage
defaults:
  - scope:
      path: "assets/test.css"
    values:

